
esphome:
  name: eve-robot
  friendly_name: Eve Robot Girl
  min_version: 2025.11.0
  includes:
    - sd_driver.h

font:
  - file: "gfonts://JetBrains Mono"
    id: robot_font
    size: 35
    glyphs: >-
      !"%()+=,-_. \|/0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzéëèỏ'

# === IMAGES ===
image:
  - file: "images/neutral.png"
    id: img_neutral
    type: RGB565
  - file: "images/eyes_closed.png"
    id: img_eyes_closed
    type: RGB565
  - file: "images/happy.png"
    id: img_happy
    type: RGB565
  - file: "images/surprised.png"
    id: img_surprised
    type: RGB565
  - file: "images/mouth_closed.png"
    id: img_mouth_closed
    type: RGB565
  - file: "images/mouth_open1.png"
    id: img_mouth_open1
    type: RGB565
  - file: "images/mouth_open2.png"
    id: img_mouth_open2
    type: RGB565
  - file: "images/mouth_open3.png"
    id: img_mouth_open3
    type: RGB565
  - file: "images/mini.png"
    id: img_mini_neutral
    type: RGB565
  - file: "images/angry_redalert.png"
    id: img_angry_redalert
    type: RGB565

# === HARDWARE ===

packages:
  hardware_core: !include packages/hardware_core.yaml
  ui_lvgl: !include packages/ui_lvgl.yaml
  scripts: !include packages/scripts.yaml
  sensors: !include packages/sensors.yaml
